#ifndef MODEL_DATA_H
#define MODEL_DATA_H

// This file is generated by ml/convert_model.py
// It contains the TFLite model as a C byte array.
// Declarations only — the binary model data is defined in model_data.cpp
#ifdef __cplusplus
extern "C" {
#endif

extern const unsigned char g_model_data[];
extern const int g_model_data_len;

#ifdef __cplusplus
}
#endif

#endif
